from __future__ import annotations

import json
import re
from pathlib import Path


MANAGED_TASK_MODE = "managed"
EXTERNAL_TASK_MODE = "external"
MANAGED_TASK_NAME_PATTERN = re.compile(r"^control_plane_[A-Za-z0-9_-]{1,64}$")


def default_managed_daily() -> dict[str, object]:
    return {
        "startup": True,
        "recruit": True,
        "recruit_times": 4,
        "infrast": True,
        "mall": True,
        "visit_friends": True,
        "shopping": True,
        "credit_fight": False,
        "fight": True,
        "stage": "",
        "fight_times": 999,
        "series": 0,
        "medicine": 0,
        "medicine_expire_days": 0,
        "stone": 0,
        "award": True,
        "mail": True,
    }


def is_managed_maa_config(config: dict[str, object]) -> bool:
    return config.get("task_mode") == MANAGED_TASK_MODE


def validate_managed_daily(config: dict[str, object]) -> tuple[str, ...]:
    if not is_managed_maa_config(config):
        return ()
    errors: list[str] = []
    task_name = config.get("task_name")
    if not isinstance(task_name, str) or not MANAGED_TASK_NAME_PATTERN.fullmatch(task_name):
        errors.append("Managed MAA task name is invalid.")
    options = config.get("managed_daily")
    if not isinstance(options, dict):
        return (*errors, "Managed MAA daily settings are required.")

    boolean_keys = (
        "startup",
        "recruit",
        "infrast",
        "mall",
        "visit_friends",
        "shopping",
        "credit_fight",
        "fight",
        "award",
        "mail",
    )
    for key in boolean_keys:
        if not isinstance(options.get(key), bool):
            errors.append(f"Managed MAA setting '{key}' must be enabled or disabled.")
    if not any(options.get(key) is True for key in ("startup", "recruit", "infrast", "mall", "fight", "award")):
        errors.append("At least one managed MAA daily task must be enabled.")

    _integer_range(errors, options, "recruit_times", 0, 99)
    _integer_range(errors, options, "fight_times", 1, 2_147_483_647)
    _integer_range(errors, options, "series", -1, 10)
    _integer_range(errors, options, "medicine", 0, 999)
    _integer_range(errors, options, "medicine_expire_days", 0, 99)
    _integer_range(errors, options, "stone", 0, 99)
    if not isinstance(options.get("stage"), str):
        errors.append("Managed MAA fight stage must be text.")
    return tuple(errors)


def render_managed_task_toml(config: dict[str, object]) -> str:
    errors = validate_managed_daily(config)
    if errors:
        raise ValueError(" ".join(errors))
    options = config["managed_daily"]
    assert isinstance(options, dict)
    blocks = [
        "# Generated by Game Automation Control Plane. Edit the job in Control Plane.",
        "",
    ]
    if options["startup"]:
        blocks.extend(
            _task_block(
                "开始唤醒",
                "StartUp",
                {"client_type": "Official", "start_game_enabled": True},
            )
        )
    if options["recruit"]:
        blocks.extend(
            _task_block(
                "自动公招",
                "Recruit",
                {
                    "refresh": True,
                    "select": [3, 4, 5],
                    "confirm": [3, 4, 5],
                    "times": options["recruit_times"],
                },
            )
        )
    if options["infrast"]:
        blocks.extend(
            _task_block(
                "基建换班",
                "Infrast",
                {
                    "facility": [
                        "Mfg",
                        "Trade",
                        "Power",
                        "Control",
                        "Reception",
                        "Office",
                        "Dorm",
                    ]
                },
            )
        )
    if options["mall"]:
        blocks.extend(
            _task_block(
                "信用与购物",
                "Mall",
                {
                    "visit_friends": options["visit_friends"],
                    "shopping": options["shopping"],
                    "credit_fight": options["credit_fight"],
                },
            )
        )
    if options["fight"]:
        blocks.extend(
            _task_block(
                "理智作战",
                "Fight",
                {
                    "stage": str(options["stage"]).strip(),
                    "medicine": options["medicine"],
                    "medicine_expire_days": options["medicine_expire_days"],
                    "stone": options["stone"],
                    "times": options["fight_times"],
                    "series": options["series"],
                },
            )
        )
    if options["award"]:
        blocks.extend(
            _task_block(
                "领取奖励",
                "Award",
                {"award": True, "mail": options["mail"]},
            )
        )
    return "\n".join(blocks).rstrip() + "\n"


def write_managed_task(config_dir: str | Path, config: dict[str, object]) -> Path:
    task_name = str(config["task_name"])
    task_dir = Path(config_dir) / "tasks"
    task_dir.mkdir(parents=True, exist_ok=True)
    destination = task_dir / f"{task_name}.toml"
    temporary = task_dir / f".{task_name}.toml.tmp"
    temporary.write_text(render_managed_task_toml(config), encoding="utf-8")
    temporary.replace(destination)
    return destination


def expected_managed_task_names(config: dict[str, object]) -> tuple[str, ...]:
    options = config.get("managed_daily")
    if not isinstance(options, dict):
        return ()
    mapping = (
        ("startup", "开始唤醒"),
        ("recruit", "自动公招"),
        ("infrast", "基建换班"),
        ("mall", "信用与购物"),
        ("fight", "理智作战"),
        ("award", "领取奖励"),
    )
    return tuple(name for key, name in mapping if options.get(key) is True)


def _integer_range(
    errors: list[str],
    options: dict[str, object],
    key: str,
    minimum: int,
    maximum: int,
) -> None:
    value = options.get(key)
    if isinstance(value, bool) or not isinstance(value, int) or not minimum <= value <= maximum:
        errors.append(f"Managed MAA setting '{key}' must be between {minimum} and {maximum}.")


def _task_block(name: str, task_type: str, params: dict[str, object]) -> list[str]:
    rendered = ", ".join(f"{key} = {_toml_value(value)}" for key, value in params.items())
    return [
        "[[tasks]]",
        f"name = {_toml_value(name)}",
        f"type = {_toml_value(task_type)}",
        f"params = {{ {rendered} }}",
        "",
    ]


def _toml_value(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, list):
        return "[" + ", ".join(_toml_value(item) for item in value) + "]"
    raise TypeError(f"Unsupported TOML value: {type(value).__name__}")


__all__ = [
    "EXTERNAL_TASK_MODE",
    "MANAGED_TASK_MODE",
    "default_managed_daily",
    "expected_managed_task_names",
    "is_managed_maa_config",
    "render_managed_task_toml",
    "validate_managed_daily",
    "write_managed_task",
]
